# Generated by Django 4.2.3 on 2023-07-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='created',
        ),
    ]
